volumes:
  starfleetDb:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: useradmin
      POSTGRES_DB: starfleetDb

    ports:
      - "5432:5432"

    volumes:
      - starfleetDb:/var/lib/postgresql/data