CREATE TABLE STARSHIPS (
	starship_id serial PRIMARY KEY,
	name varchar(200) NOT NULL,
	CLASS varchar(100),
	LAUNCH_YEAR int,
	status varchar(10) check(status IN('ACTIVE', 'INACTIVE', 'ON MISSION', 'MAINTENANCE', 'DESTROYED')),
	PHOTO_URL VARCHAR(100)
);

INSERT INTO starships (NAME, CLASS, LAUNCH_YEAR, STATUS, PHOTO_URL)VALUES ('ENTERPRISE', 'GALAXY', 2306, 'ACTIVE', 'https://www.deviantart.com/jetfreak-7/art/USS-Enterprise-D-825175448');


CREATE TABLE CREW_MEMBERS (
	MEMBER_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
    RANK VARCHAR(50) CHECK (RANK IN ('ENSIGN', 'LIEUTENANT', 'COMMANDER', 'CAPTAIN', 'ADMIRAL')),
    SPECIES VARCHAR(100),
    AGE INT,
    STARSHIP_ID INT,
    PHOTO_URL VARCHAR(100),
    ROLE VARCHAR(100),
    FOREIGN KEY (STARSHIP_ID) REFERENCES STARSHIPS(starship_id) ON DELETE SET NULL
);

INSERT INTO CREW_MEMBERS (NAME, RANK, SPECIES, AGE, STARSHIP_ID, PHOTO_URL, ROLE) VALUES ('Jean-Luc Picard', 'CAPTAIN', 'Human', 60, 2, NULL, 'COMMANDER');


CREATE TABLE MISSIONS (
    MISSION_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    GOAL TEXT, --MIGHT BE AN ERROR, 'CAUSE OF 'TEXT' TYPE
    status VARCHAR(50) CHECK (status IN ('PLANNED', 'IN PROGRESS', 'COMPLETED', 'FAIL')),
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    STARSHIP_ID INT,
    FOREIGN KEY (STARSHIP_ID) REFERENCES STARSHIPS(STARSHIP_ID) ON DELETE CASCADE
);


--CREATE TABLE CREW_SHIPS (
--    CREW_SHIPS_ID SERIAL PRIMARY KEY,
--    MEMBER_id INT,
--    SHIP_id INT,
--    START_DATE TIMESTAMP,
--    END_DATE TIMESTAMP,
--    ROLE VARCHAR(100),
--    FOREIGN KEY (MEMBER_id) REFERENCES CREW_MEMBERS(MEMBER_ID) ON DELETE CASCADE,
--    FOREIGN KEY (SHIP_id) REFERENCES STARSHIPS(starship_id) ON DELETE CASCADE
--);

